Updated documentation for ServicePulse October release
Particular/docs.particular.net pull request #5071
Opened 2020-10-19 13:52 UTC by seanfarmar

2020-10-19 14:48 UTC, timbussmann requested changes

2020-10-19 14:48 UTC, timbussmann commented on servicepulse/intro-archived-messages.md
> +## About message delition
```suggestion
## About message deletion
```

2020-10-19 16:50 UTC, sergioc commented on servicepulse/intro-archived-messages.md
> +## About message delition
```suggestion
## About deleting messages
```

2020-10-20 07:13 UTC, sergioc commented on servicepulse/intro-archived-messages.md
>  ## Archiving messages
```suggestion
## Deleting messages
```

2020-10-20 08:01 UTC, timbussmann approved these changes

2020-10-20 08:47 UTC, sergioc approved these changes

2020-10-20 12:47 UTC, merged