New instance must have different name
Particular/docs.particular.net pull request #5198
Opened 2021-01-26 12:07 UTC by yvesgoeleven

2021-01-26 12:13 UTC, ramonsmits requested changes
This is not enough, endpoints send heartbeats to the previous SC queue and would need to send them to the new SC queue.

This doesn't seem to be mentioned in the docs too. 

I think it is just better to remove the whole side-by-side section from this upgrade guide as it is very complex and flawed.

2021-01-26 12:13 UTC, ramonsmits commented on servicecontrol/upgrades/1to2.md
> +2. Add a new version 2 instance of ServiceControl, which has a new name, and configure it to ingest messages from the error and audit queues that the version 1 instance was previously configured to i
```suggestion
2. Add a new version 2 instance of ServiceControl, which has a new unique name, and configure it to ingest messages from the error and audit queues that the version 1 instance was previously configured to ingest messages from.
```

2021-01-27 06:18 UTC, WilliamBZA submitted a review, later dismissed

2021-01-27 06:18 UTC, WilliamBZA commented on servicecontrol/upgrades/1to2.md
> +2. Add a new version 2 instance of ServiceControl, which has a new unique name, and configure it to ingest messages from the error and audit queues that the version 1 instance was previously configur
```suggestion
2. Add a new version 2 instance of ServiceControl, with a name different to the version 1 instance name, and configure it to ingest messages from the error and audit queues that the version 1 instance was previously configured to ingest messages from.
```

2021-03-16 21:26 UTC, ramonsmits approved these changes

2021-03-16 21:29 UTC, merged