Update RabbitMQ docs to core V8
Particular/docs.particular.net pull request #5230
Opened 2021-02-23 11:06 UTC by SzymonPobiega

2021-02-24 16:20 UTC, timbussmann commented on Snippets/Rabbit/Rabbit_7/UpgradeGuides/6to7/Upgrade.cs
> +        transport.ClientCertificate = new X509Certificate2("path", "password");
use object initializers syntax instead?

2021-02-24 16:20 UTC, timbussmann commented on transports/rabbitmq/connection-settings_prefetch-control_rabbit_[7,).partial.md
> +By default the prefetch count is calculated by multiplying [maximum concurrency](/nservicebus/operations/tuning.md#tuning-concurrency) by the prefetch multiplier of 3. The default prefetch count calc
```suggestion
By default the prefetch count is calculated by multiplying [maximum concurrency](/nservicebus/operations/tuning.md#tuning-concurrency) by the prefetch multiplier of 3. The default prefetch count calculation can be overridden with a custom algorithm. The configured concurrency setting is passed as an input to the calculation function.
```

2021-03-01 10:04 UTC, mauroservienti requested changes

2021-03-01 10:04 UTC, mauroservienti commented on transports/upgrades/rabbitmq-6to7.md
> +To use Azure Service Bus Transport for NServiceBus, create a new instance `AzureServiceBusTransport` and pass it to `EndpointConfiguration.UseTransport`.
```suggestion
To use the RabbitMQ transport for NServiceBus, create a new instance of the `RabbitMQTransport` and pass it to `EndpointConfiguration.UseTransport`.
```

2021-03-01 10:04 UTC, mauroservienti commented on transports/upgrades/rabbitmq-6to7.md
> +The RabbitMQ Transport configuration options that have not been changed have been moved to the `RabbitMQTransport` class. See the following table for further information:
```suggestion
The RabbitMQ transport configuration options that have not been changed have been moved to the `RabbitMQTransport` class. See the following table for further information:
```

2021-03-01 14:07 UTC, mauroservienti approved these changes
Does it make sense to change also these two?

2021-03-01 14:07 UTC, mauroservienti commented on Snippets/Rabbit/Rabbit_7/UpgradeGuides/6to7/Upgrade.cs
> +        transport.ClientCertificate = new X509Certificate2("path", "password");
```suggestion
        var transport = new RabbitMQTransport(Topology.Conventional, "host=localhost")
        {
            ClientCertificate = new X509Certificate2("path", "password")
        };
```

2021-03-01 14:07 UTC, mauroservienti commented on Snippets/Rabbit/Rabbit_7/UpgradeGuides/6to7/Upgrade.cs
> +        transport.PrefetchCountCalculation = concurrency => concurrency * 7;
```suggestion
        var transportWithFixedPrefetchCount = new RabbitMQTransport(Topology.Conventional, "host=localhost")
        {
            PrefetchCountCalculation = _ => 100
        };

        //or

        var transportWithConcurrencyBasedPrefetchCount = new RabbitMQTransport(Topology.Conventional, "host=localhost")
        {
            PrefetchCountCalculation = concurrency => concurrency * 7
        };
```

2021-03-02 08:57 UTC, merged