Dynamic strikethrough for unsupported versions
Particular/docs.particular.net pull request #5251
Opened 2021-03-11 14:44 UTC by ramonsmits

Does not require the version script to run only for applying strikethrough styling.

2021-03-11 15:24 UTC, andreasohlund approved these changes

2021-03-11 15:28 UTC, DavidBoike commented
Do you intend to also remove the markup strikethrough? Or is this only supposed to handle when the script hasn't run in awhile?

2021-03-11 15:33 UTC, DavidBoike commented
Needs to be applied on http://localhost:5000/nservicebus/upgrades/all-versions too.

Why isn't the strikethrough action applied to the first column as well?

2021-03-11 15:38 UTC, DavidBoike requested changes
To put it all in one review:

* Do the IIFE
* Add to http://localhost:5000/nservicebus/upgrades/support-policy
* Add to http://localhost:5000/nservicebus/upgrades/all-versions
* Probably apply style to first column?

2021-03-11 15:38 UTC, DavidBoike commented on nservicebus/upgrades/supported-versions.js
> +var now = new Date();
Could you please wrap this whole thing in an immediately-executed function expression (IIFE) so we don't further pollute the global namespace?

```
'use strict';
(function () {
    // All your code
} ());

2021-03-11 15:48 UTC, ramonsmits commented
> * Probably apply style to first column?

That is a link and for that reason the color isn't applied as links us the link color.

> Do you intend to also remove the markup strikethrough?

The code isn't removing any styling. It only applies in case it detects a row has an unsupported version.

> Or is this only supposed to handle when the script hasn't run in awhile?

It could be a full replacement for the script. The strikethrough is only a visual thing. The dates in the columns are leading.

2021-03-11 16:09 UTC, ramonsmits commented
@DavidBoike I removed the `maroon` color to only apply strike through.

2021-03-16 13:34 UTC, DavidBoike approved these changes

2021-03-16 13:34 UTC, merged