SQS migration mode options
Particular/docs.particular.net pull request #5480
Opened 2021-09-13 09:52 UTC by tmasternak

2021-09-14 06:15 UTC, tmasternak commented on transports/sqs/topology_pub-sub_sqs_[5,).partial.md
> +Native support for SNS was [introduced in version 5](/transports/upgrades/amazonsqs-4to5.md#native-publish-subscribe) of the Amazon SQS transport. In able to upgrade from message-driven publish-subsc
```suggestion
Starting with [version 5](/transports/upgrades/amazonsqs-4to5.md#native-publish-subscribe) the SQS Transport uses SNS for publish-subscribe messaging. Communication with endpoints running on older versions is still possible via publish-subscribe compatibility mode. A publisher running in this mode will publish events both through SNS topics and unicast messaging destined to input queues of the older endpoints.

The compatibility mode requires SNS topology information that is queried by the endpoint using Amazon SQS client SDK. The API can be throttled by AWS - mostly in high-throughput scenarios that occur when many different types of events are being published at the same time. As a result, version 5.4 of the NServiceBus SQS Transport, introduced a caching mechanism that prevents API throttling from interfering with message processing in most of the scenarios. 
```

2021-09-14 06:15 UTC, tmasternak commented on transports/sqs/topology_pub-sub_sqs_[5,).partial.md
> +The topic cache and subscription cache can be extended to prevent additional rate limiting. The message visibility timeout can be extended if messages are returned to the queue before NServiceBus had
```suggestion
The default values of cache invalidation and message visibility timeouts can be changed using publish-subscribe compatibility mode [settings](transports/sqs/configuration-options.md#message-driven-pubsub-compatibility-mode).
```

2021-09-14 08:03 UTC, mauroservienti requested changes

2021-09-14 08:03 UTC, mauroservienti commented on Snippets/Sqs/Sqs_5/Usage.cs
> +        migrationSettings.TopicCacheTtl(TimeSpan.FromSeconds(30));
```suggestion
        migrationSettings.TopicCacheTTL(TimeSpan.FromSeconds(30));
```

2021-09-15 21:20 UTC, dvdstelt approved these changes

2021-09-16 13:36 UTC, mauroservienti approved these changes

2021-09-16 14:38 UTC, merged