Add kissmetrics to quickstart, fix ordering in quickstart page 3
Particular/docs.particular.net pull request #5610
Opened 2022-01-21 16:08 UTC by soujay

Related : [#3066](https://github.com/Particular/DeveloperEducation/issues/3066)
This update has the following changes.
1.  Add kissmetrics to quickstart tutorial to capture the following events 
     - when solution runs 
     - when a message is sent
2. Fix the ordering of the steps mentioned in Page 3 of the quickstart tutorial

2022-01-21 23:00 UTC, DavidBoike requested changes

2022-01-24 17:44 UTC, DavidBoike commented on tutorials/quickstart/Solution/ClientUI/wwwroot/Content/app.js
> +    _kms('//scripts.kissmetrics.io/' + _kmk + '.2.js');
Oh no, I didn't mean remove ALL indentation, just that the indentation should be correct! Should just have shifted everything to the left 4 spaces is all!

2022-01-25 00:24 UTC, soujay commented on tutorials/quickstart/Solution/ClientUI/wwwroot/Content/app.js
> +    _kms('//scripts.kissmetrics.io/' + _kmk + '.2.js');
@DavidBoike - Fixed it. Please review

2022-01-25 14:37 UTC, DavidBoike approved these changes

2022-01-25 19:03 UTC, merged