Adding documentation related to raven 5 persistence for Audit
Particular/docs.particular.net pull request #5887
Opened 2022-10-18 13:22 UTC by WojcikMike

Added the following pages:
 - persistence page for SC.Audit
 - Modified the page defining expiration

When we agree on the wording we should create a page describing persistence for the error instance

2022-10-19 03:51 UTC, mikeminutillo commented on servicecontrol/audit-instances/persistence.md
> +ServiceControl audit instances store their data in an RavenDB embedded database. In the ServiceControl.Audit version 4.26 and up, new instances store their data in RavenDB version 5. Instances less t
Using [version language guidance](https://github.com/particular/docs.particular.net#version-language)

```suggestion
ServiceControl audit instances store their data in a RavenDB embedded database. In ServiceControl.Audit version 4.26 and above, new instances store their data in RavenDB version 5. Instances created by version 4.25 and below use RavenDB version 3.5.
```

2022-10-19 03:51 UTC, mikeminutillo commented on servicecontrol/audit-instances/persistence.md
> +Upgrading ServiceControl.Audit instances into version 4.26 or higher does not change the database version. So instance that uses RavenDB version 3.5 upgraded to the newest version will still be using
```suggestion
Upgrading ServiceControl.Audit instances into version 4.26 or higher does not change the database version. So instance that use RavenDB version 3.5 upgraded to the newest version will still be using RavenDB version 3.5.
```

2022-10-19 03:51 UTC, mikeminutillo commented on servicecontrol/how-purge-expired-data.md
> +Expiration of error and audit data is implemented by runnig a reccuring task that checks the documents for old data and deleting the rows that should be deleted. Changing the expiration setting resul
```suggestion
Expiration of error and audit data is implemented by a reccuring task that checks the documents for old data and deletes documents that have expired. Changing the expiration setting results in it being picked up during the next time the service is run. 
```

2022-10-19 03:51 UTC, mikeminutillo commented on servicecontrol/how-purge-expired-data.md
> +In the ServiceControl.Audit version 4.26 and up expiration is done using the persistance mechanisms, that results in metadata key to be stored with every message. Thanks to that, purging of the data
Using version language guidance.

```suggestion
In ServiceControl.Audit version 4.26 and above expiration is handled by the database automatically. Each audited message contains a metadata key that tells the database when to remove it. When the expiration setting changes, the new value is only applied to new audit data. Existing audit meta is not changed. Messages already in the database are not affected by the change to the expiration setting.
```

2022-10-19 07:23 UTC, andreasohlund commented on servicecontrol/how-purge-expired-data.md
> +## Differences in purge implementations
```suggestion
## Differences in message rentention implementations
```

2022-10-20 13:34 UTC, mauroservienti requested changes

2022-10-20 13:34 UTC, mauroservienti commented on servicecontrol/how-purge-expired-data.md
> +Expiration of error and audit data is implemented by a reccuring task that checks the documents for old data and deletes documents that have expired. Changing the expiration setting results in it bei
```suggestion
The expiration of error and audit data is implemented by a recurring task that checks and deletes expired documents. Changing the expiration setting results in it being picked up the next time the service is run. 
```

2022-10-20 13:34 UTC, mauroservienti commented on servicecontrol/how-purge-expired-data.md
> +In ServiceControl.Audit version 4.26 and above expiration is handled by the database automatically. Each audited message contains a metadata key that tells the database when to remove it. When the ex
```suggestion
In ServiceControl.Audit version 4.26 and above expiration is handled by the database automatically. Each audited message contains a metadata key that tells the database when to remove it. When the expiration setting changes, the new value is only applied to new audit data. Metadata for already ingested messages is not changed. Only new audited messages are affected by the change to the expiration setting.
```

2022-10-20 13:34 UTC, mauroservienti commented on servicecontrol/audit-instances/persistence.md
> +Upgrading ServiceControl.Audit instances into version 4.26 or higher does not change the database version. So instance that use RavenDB version 3.5 upgraded to the newest version will still be using
```suggestion
Upgrading ServiceControl.Audit instances to version 4.26 or higher does not change the database version. Instances using RavenDB version 3.5, when upgraded to the newest version, will still be using RavenDB version 3.5.
```

2022-10-20 14:25 UTC, WojcikMike commented
We probably should wait with this PR until we actually release SC right?

2022-10-20 14:30 UTC, mauroservienti approved these changes

2022-10-21 06:35 UTC, andreasohlund commented on servicecontrol/audit-instances/persistence.md
> +ServiceControl audit instances store their data in a RavenDB embedded database. In ServiceControl.Audit version 4.26 and above, new instances store their data in RavenDB version 5. Instances created
```suggestion
ServiceControl audit instances store their data in a RavenDB embedded database. In ServiceControl.Audit version 4.26 and above new instances use RavenDB version 5. Instances created by version 4.25 and below use RavenDB version 3.5.
```

2022-10-21 06:35 UTC, andreasohlund commented on servicecontrol/audit-instances/persistence.md
> +Upgrading ServiceControl.Audit instances to version 4.26 or higher does not change the database version. Instances using RavenDB version 3.5, when upgraded to the newest version, will still be using
We should link to the upgrade guide that @mikeminutillo is working on

2022-10-21 06:35 UTC, andreasohlund commented on servicecontrol/persistence.md
> +WARNING: The ServiceControl Audit RavenDB embedded instance is used exclusively by ServiceControl and is not intended for external manipulation or modifications.
```suggestion
WARNING: The ServiceControl RavenDB embedded database is used exclusively by ServiceControl and is not intended for external manipulation or modifications.
```

2022-10-21 06:35 UTC, andreasohlund commented on servicecontrol/audit-instances/persistence.md
> +WARNING: The ServiceControl Audit RavenDB embedded instance is used exclusively by ServiceControl and is not intended for external manipulation or modifications.
```suggestion
WARNING: The ServiceControl Audit RavenDB embedded database is used exclusively by ServiceControl and is not intended for external manipulation or modifications.
```

2022-10-24 13:13 UTC, merged