Quick start GA4 update
Particular/docs.particular.net pull request #6076
Opened 2023-05-29 21:19 UTC by cquirosj

Pushing events from the "Quick Start" sample to Google Analytics 4

2023-06-05 06:19 UTC, abparticular approved these changes

2023-06-21 13:36 UTC, abparticular requested changes

2023-06-26 22:12 UTC, TravisNickels commented on tutorials/quickstart/Solution/ClientUI/wwwroot/Content/app.js
> +gtag('config', window.GA4_MEASUREMENT_ID,{ 'debug_mode': true });
```suggestion
gtag('config', window.GA4_MEASUREMENT_ID);
```

2023-06-26 22:15 UTC, TravisNickels approved these changes

2023-06-26 22:16 UTC, abparticular approved these changes

2023-06-26 22:17 UTC, merged