update NSB step by step tutorial to NSB 8
Particular/docs.particular.net pull request #6137
Opened 2023-07-16 06:23 UTC by soujay

2023-07-17 11:45 UTC, ramonsmits commented
@soujay is it intentional that you removed the v7 variant?

2023-07-17 13:46 UTC, DavidBoike commented
@ramonsmits Yes, tutorials should not teach you how to use NServiceBus with an old version.

2023-07-18 21:44 UTC, DavidBoike requested changes
Some more changes (outside the current set, so I can't do a line comment) are also needed:

* [Lesson 1 Create a solution](https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/#exercise-create-a-solution) change to assume net6 or higher.
  * We don't have to talk about CompletedTask API anymore. The minimum frameworks supported by NServiceBus 8 already have it.
* [Lesson 1 Configure an endpoint](https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/#exercise-configure-an-endpoint) take out the [paragraph about C# 7.1 features](https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/#exercise-configure-an-endpoint) - with net6.0 you get them for free.
  * [This section](https://github.com/Particular/docs.particular.net/blob/master/tutorials/nservicebus-step-by-step/1-getting-started/tutorial.md?plain=1#L63-L69) should not mention C# 7.1, should not have a `PreCsharp7-1AsyncBoilerplate` snippet,rename the `AsyncMain` snippet to `Main`, and rewrite the sentence before (line 67) so that it only talks about the Main method.
  * Look other places for "AsyncMain" (in all 5 lessons) and clean that up as well.

2023-07-18 21:44 UTC, DavidBoike commented on tutorials/nservicebus-step-by-step/1-getting-started/tutorial.md
>  NOTE: You can also build the solution in .NET Core by selecting the **Console App (.NET Core)** project type when you create a new project.
```suggestion
This tutorial uses NServiceBus version 8, .NET 6, and assumes an up-to-date installation of [Visual Studio 2022](https://www.visualstudio.com/downloads/).

NOTE: NServiceBus 8 also [supports .NET Framework 4.7.2 or higher](/nservicebus/operations/dotnet-framework-version-requirements.md), but [new applications should be built on .NET 6 or higher](https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/). 
```

2023-07-18 21:44 UTC, DavidBoike commented on tutorials/nservicebus-step-by-step/3-multiple-endpoints/Snippets/Core_8/Lesson3.cs
> +            await endpointInstance.SendLocal(command, context.CancellationToken)
These are included together for ease of writing the docs, but the token from the message handler context shouldn't be passed to the endpointInstance methods. Revert this and suppress the warning using an attribute on the SendTypes method. Set the justification in the attribute to be "Parameters only both included for ease of documentation"

2023-07-18 21:44 UTC, DavidBoike commented on tutorials/nservicebus-step-by-step/3-multiple-endpoints/Snippets/Core_8/Lesson3.cs
> +            await endpointInstance.Send(command, context.CancellationToken)
Here too

2023-07-18 21:44 UTC, DavidBoike commented on tutorials/nservicebus-step-by-step/3-multiple-endpoints/Snippets/Core_8/Lesson3.cs
> +            await endpointInstance.Send("Destination", command, context.CancellationToken)
And here

2023-07-20 14:12 UTC, DavidBoike approved these changes
Just one nitpick

2023-07-20 14:52 UTC, merged