Added Parellism section to NServiceBus tuning guidance
Particular/docs.particular.net pull request #6677
Opened 2024-05-29 15:51 UTC by ramonsmits

- [ ] Improve upgrade guide for RabbitMQ transport where concurrency behavior changed

2024-05-29 22:00 UTC, johnsimons requested changes

2024-05-29 22:00 UTC, johnsimons commented on nservicebus/operations/tuning.md
> +For example, when handlers that invoke synchrounous code only will block when the transport has a fully asynchronous design and handler will be processed sequentially.
```suggestion
```

2024-05-29 22:00 UTC, johnsimons commented on nservicebus/operations/tuning.md
> +For example, when handlers that invoke synchrounous code only will block when the transport has a fully asynchronous design and handler will be processed sequentially.
I think we better off without it

2024-05-30 03:15 UTC, johnsimons commented
@ramonsmits after spending a few hours on this, we decided to not over complicate it and keep it simple and link to existing documentation on the subject.
Thoughts?

2024-05-30 03:19 UTC, johnsimons approved these changes

2024-05-30 06:57 UTC, merged

2024-05-30 16:59 UTC, danielmarbach commented
LGTM