Review of audit deployment via Powershell
Particular/docs.particular.net pull request #6776
Opened 2024-07-26 06:21 UTC by abparticular

2024-07-26 07:54 UTC, tmasternak approved these changes

2024-07-26 15:32 UTC, bording requested changes
This change is not correct. The page is detailing the PowerShell Gallery version of the module, and the name of the command is `Get-ServiceControlManagementCommands` in the gallery version, regardless of version.

On the 4.x version of the page, there is a NOTE box that mentions the legacy version of the module that is installed as part of running the 4.x installer.

The PowerShell Gallery version is the preferred version to use and can be used for 4.x as well, so there's no reason to try and document the legacy version at this point.

I would suggest closing this PR, or perhaps removing the snippet change and keeping the reviewed date update.

2024-07-29 07:06 UTC, abparticular commented
@bording I've removed the versioning #ifdef in the snippet.  I still think the name needs updating since the current doc site refers to the previous name.

2024-07-29 15:18 UTC, bording commented
> @bording I've removed the versioning #ifdef in the snippet. I still think the name needs updating since the current doc site refers to the previous name.

Good call. That change was lost in the #ifdef stuff when I first took a look at the PR!

2024-07-29 15:18 UTC, bording approved these changes

2024-07-29 23:37 UTC, merged